// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication9.Models;

#nullable disable

namespace WebApplication9.Migrations.Employee_ProjectDb
{
    [DbContext(typeof(Employee_ProjectDbContext))]
    [Migration("20240906130116_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApplication9.Models.Employee_Project", b =>
                {
                    b.Property<int>("e_p_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("e_p_id"));

                    b.Property<int>("amount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("effort_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("end_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("goals")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("e_p_id");

                    b.ToTable("Employee_Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
