// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication9.Models;

#nullable disable

namespace WebApplication9.Migrations.EffortDb
{
    [DbContext(typeof(EffortDbContext))]
    [Migration("20240906130214_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApplication9.Models.Effort", b =>
                {
                    b.Property<int>("effort_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("effort_id"));

                    b.Property<int>("employee_id")
                        .HasColumnType("integer");

                    b.Property<int>("project_id")
                        .HasColumnType("integer");

                    b.HasKey("effort_id");

                    b.ToTable("Efforts");
                });
#pragma warning restore 612, 618
        }
    }
}
